package se.yrgo.services.customers;

import org.springframework.jdbc.BadSqlGrammarException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import se.yrgo.dataaccess.CustomerDao;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String TBL_CUSTOMER = "CREATE TABLE TBL_CUSTOMER(CUSTOMER_ID VARCHAR(10), COMPANY_NAME VARCHAR(200), EMAIL VARCHAR(100), TELEPHONE VARCHAR(100), NOTES VARCHAR(300))";
    private static final String INSERT_TO_CUSTOMER = "INSERT INTO TBL_CUSTOMER(CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?,?,?,?,?)";
    private static final String TBL_CALL = "CREATE TABLE TBL_CALL(CALL_ID INTEGER GENERATED BY DEFAULT AS IDENTITY, CUSTOMER_ID VARCHAR(10), TIME_AND_DATE DATE, NOTES VARCHAR(300))";
    private static final String INSERT_TO_CALL = "INSERT INTO TBL_CALL(CUSTOMER_ID, TIME_AND_DATE, NOTES) VALUES (?,?,?)";

    private JdbcTemplate jdbcTemplate;

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
        createTables();
    }


    private void createTables() {
        try {
            jdbcTemplate.execute("DROP TABLE TBL_CUSTOMER IF EXISTS");
            jdbcTemplate.execute(TBL_CUSTOMER);
        } catch (Exception e) {
            System.out.println("Issues creating TBL_CUSTOMER " + e.getMessage());
        }
        try {
            jdbcTemplate.execute("DROP TABLE TBL_CALL IF EXISTS");
            jdbcTemplate.execute(TBL_CALL);
        } catch (Exception e) {
            System.out.println("Issues creating TBL_CALL: " + e.getMessage());
        }
    }

    @Override
    public void create(Customer customer) {
        jdbcTemplate.update(INSERT_TO_CUSTOMER, customer.getCustomerId(), customer.getCompanyName(), customer.getEmail(), customer.getTelephone(), customer.getNotes());
    }

    @Override
    public Customer getById(String customerId) {
        return jdbcTemplate.queryForObject("SELECT * FROM TBL_CUSTOMER WHERE CUSTOMER_ID=?", new CustomerRowMapper(), customerId);

    }

    @Override
    public List<Customer> getByName(String name) {
        return jdbcTemplate.query("SELECT * FROM TBL_CUSTOMER WHERE COMPANY_NAME=?", new CustomerRowMapper(), name);
    }

    @Override
    public void update(Customer customerToUpdate) {
        jdbcTemplate.update("UPDATE TBL_CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=? WHERE CUSTOMER_ID=?",
                customerToUpdate.getCompanyName(),
                customerToUpdate.getEmail(),
                customerToUpdate.getTelephone(),
                customerToUpdate.getCustomerId());
    }

    @Override
    public void delete(Customer oldCustomer) {
        jdbcTemplate.update("DELETE FROM TBL_CUSTOMER WHERE CUSTOMER_ID=?",
                oldCustomer.getCustomerId());

    }

    @Override
    public List<Customer> getAllCustomers() {
        return jdbcTemplate.query("SELECT * FROM TBL_CUSTOMER", new CustomerRowMapper());
    }

    @Override
    public Customer getFullCustomerDetail(String customerId) {
        Customer customer = getById(customerId);

        List<Call> calls = jdbcTemplate.query(
                "SELECT * FROM TBL_CALL WHERE CUSTOMER_ID=?",
                (rs, rowNum) -> new Call(
                        rs.getString("NOTES"),
                        rs.getTimestamp("TIME_AND_DATE")
                ), customerId);

        customer.setCalls(calls);
        return customer;
    }

    @Override
    public void addCall(Call newCall, String customerId) {
        jdbcTemplate.update(INSERT_TO_CALL, customerId, new java.sql.Date(newCall.getTimeAndDate().getTime()), newCall.getNotes());
    }

    class CustomerRowMapper implements RowMapper<Customer> {
        @Override
        public Customer mapRow(ResultSet rs, int rowNum) throws SQLException {
            String customerId = rs.getString("CUSTOMER_ID");
            String companyName = rs.getString("COMPANY_NAME");
            String email = rs.getString("EMAIL");
            String telephone = rs.getString("TELEPHONE");
            String notes = rs.getString("NOTES");
            return new Customer("" + customerId, companyName, email, telephone, notes);
        }
    }
}
